title: Sångbok
email: actimia1@gmail.com
description: >-
  En elektronisk sångbok med alla favoriterna.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: actim1a
github_username:  actimia

collections:
  songs:
    output: true
    permalink: /songs/:title/

defaults:
  - scope:
      path: ""
    values:
      layout: "base"
  - scope:
      path: ""
      type: songs
    values:
      layout: "song"
  - scope:
      path: "_songs/english"
      type: songs
    values:
      category: In english
  - scope:
      path: "_songs/swedish"
      type: songs
    values:
      category: Svenska sånger
  - scope:
      path: "_songs/snapsvisor"
      type: songs
    values:
      category: Snapsvisor
  - scope:
      path: "static/sheetmusic"
    values:
      sheetmusic: true

pwa:
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: static/js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "static/**/*.{js,css,eot,svg,ttf,woff}"
    - "**/*.html"
    - index.html
  precache_glob_ignores: # Optional
    - sw-register.js
    - "fonts/**/*"

# Build settings
markdown: kramdown
#plugins: []

exclude: [".idea", "Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", "bin"]

